explode-on-destroy: false
disable-player-in-region-checks: false
max-tax: 500.0
destroy-if-no-money: true
destroy-if-no-power: true
use-power: true
rename-cost: 500.0
help-page: https://www.spigotmc.org/resources/townships.1892/
use-town-prefixes: true
war:
  use-war: false
  declare-war-base-cost: 2000.0
  declare-war-cost-per-member: 500.0
  make-peace-base-cost: 1000.0
  make-peace-cost-per-member: 500.0
multiple-town-membership:
  allow: true
  whitelist: []