explode-on-destroy: false
max-tax: 500.0
destroy-if-no-money: true
destroy-if-no-power: true
use-power: true
rename-cost: 500.0
war:
  use-war: false
  declare-war-base-cost: 2000.0
  declare-war-cost-per-member: 500.0
  make-peace-base-cost: 1000.0
  make-peace-cost-per-member: 500.0