author: Multitallented
database: false
description: Allows you to create regions that can give buffs or debuffs to players with certain HeroClasses.
main: multitallented.redcastlemedia.bukkit.herostronghold.HeroStronghold
name: HeroStronghold
startup: postworld
version: 0.6.1-b000
depend: [Vault]
softdepend: [Heroes]
commands:
   herostrong:
      aliases: ['herostronghold', 'hs']
      description: HeroStronghold commands
      usage: /<command>
   god:
      description: Prevents you from taking any damage
      usage: /<command>
permissions:
   herostronghold.create.all:
      description: Allows you to create a HeroStronghold of any type if you have the necessary materials
      default: op
   herostronghold.admin:
      description: Lets you use admin commands
      default: op
   herostronghold.god:
      description: Lets you use /god
      default: op