author: Multitallented
database: false
author: Multitallented
authors: [chivers1234, Sevaron, Kiak]
description: Allows you to create regions that can give buffs or debuffs to players with certain HeroClasses.
main: multitallented.redcastlemedia.bukkit.herostronghold.HeroStronghold
name: HeroStronghold
startup: postworld
version: 1.2.1-b054
depend: [Vault]
softdepend: [Heroes, Towny, Factions]
commands:
   hs:
      aliases: ['herostronghold', 'herostrong']
      description: HeroStronghold commands
      usage: /<command>
permissions:
   herostronghold.create.all:
      description: Allows you to create a HeroStronghold of any type if you have the necessary materials
      default: op
   herostronghold.admin:
      description: Lets you use admin commands
      default: op
loadbefore: [Vault, Heroes]